### ISSUE TITLE
Dependency Versions

### ISSUE THREAD

**Issue by C4J** [harwey/cups4j#16]
If I understand correctly I need the followiing jars to get cup4j working. However my project also uses jasperreports which includes an older version of the httpclient jar file. Do you think it would be ok to use an older version with cups4j ?

cups4j-0.7.6.jar
commons-io-2.6.jar
**httpclient-4.5.7.jar**
simple-xml-2.7.1.jar
slf4j-api-1.7.26.jar

**httpclient-4.3.6.jar**

**Comment by harwey** [comment]
In pom.xml you can see that cups4j uses httpclient 4.5.2. 
Just give it a try with 4.3.6 and see if the communication still works. Should be easy to test.

**Comment by harwey** [comment]
Did you give it a try? What are the results?

**Comment by C4J** [comment]
It seems to work albeit from a quick check of those functions I use.
