### ISSUE TITLE
Query possible extra/advanced attributes 

### ISSUE THREAD

**Issue by kravemir** [harwey/cups4j#17]
I'm searching for alternative to standard Java Printer Job, because I wasn't able to find a way to set and/or query special printer attributes.

Mainly, I'm interest in paper type, which is printer specific. For example normal plain paper, light paper, heavy paper, labels, envelope, matte paper.. It depends on printer driver.. And, it produces better output when printing on these special papers.

Is it possible with this library to get a list of possible extra options, and also get list/specification of possible values for each option?

**Comment by barryspearce** [comment]
If the paper types are configured on the CUPS server you should be able to examine the available options using ipptool. Then these could be set as required using the attributes.
