### ISSUE TITLE
CupsClient.getPrinters() returns no printers (403)

### ISSUE THREAD

**Issue by oboehm** [harwey/cups4j#2]
CupsClient.getPrinters() normally returns a list of printers. But in our case this list was empty. By examing the log files on the CUPS server we saw, that a 403 (forbidden) was sent as answer. In this case I expect a  corresponding exception on the client site - otherwise it is hard to find the cause of an empty list.

**Comment by harwey** [comment]
Please try the snapshot version. An Exception is thrown now when HTTP status code is higher or equal to 300. In all of those cases some configuration should be wrong.

**Comment by oboehm** [comment]
Works now as expected. I get  now
`Caused by: java.io.IOException: HTTP error! Status code:  HTTP/1.1 403 Forbidden`
as exeption.
Thank you for fixing...
