### ISSUE TITLE
print jobs with multiple documents are not supported

### ISSUE THREAD

**Issue by oboehm** [harwey/cups4j#3]
To be able to print multiple documents the CUPS protocoll provides a 'create-job' operation. With 'send-document' you can send several documents. It would be nice if cups4j allows also support print jobs with more than 1 document.

**Comment by harwey** [comment]
Cups4j does not aim to provide full CUPS or IPP support. Mainly Cups4j was designed to make printing on Linux/Unix possible from Java with job status tracking. 
Can you provide some more information why it is not practicable for you to create several print jobs to print several documents?

I don't have much time to support this library so I want to extend it if new features really count for many users.

**Comment by oboehm** [comment]
Hi Harwey,

no problem - I can try to add the functionality and send you a pull request.

Background for this request: we want to add a number of documents, which should not be interrupted by other print jobs.

regards,
Oliver

**Comment by harwey** [comment]
Sounds good. 
I will leave this issue open for now.

**Comment by oboehm** [comment]
any plans when PR #5  will be merged and a new version will be released?

**Comment by harwey** [comment]
PR merged and deployed to maven central as cups4j.org 0.7.2

**Comment by harwey** [comment]
Thanks for your PR!
Harald

**Comment by harwey** [comment]
I did deploy to maven central, but it seems that this did not work. 
Sometimes it takes several hours after upload to be shown in the archives, but I do think something went wrong - without any error message.
Thanks for your hint, I will take a look why this did not work out.

**Comment by harwey** [comment]
My first upload to maven central went wrong in some way that could not be resolved. 
So in the end I had to discard version 0.7.2. The current version is 0.7.3 (https://mvnrepository.com/artifact/org.cups4j/cups4j/0.7.3)

**Comment by harwey** [comment]
Thank you Oliver for your work.

**Comment by C4J** [comment]
How backwards compatible is this new version with version 0.6.4 for example ?

David Garratt

davidgarratt@commander4j.com

**Comment by oboehm** [comment]
Should be compatible - the difference to 0.7.0 is, that 0.7.0 is published to Maven Central. The actual version 0.7.3 supports now the send-document request of IPP (https://tools.ietf.org/html/rfc8011#section-4.3.1 ). The other features (print-job) were not changed - so should be also compatible with 0.6.4
