### ISSUE TITLE
cannot work

### ISSUE THREAD

**Issue by in-my-heart** [harwey/cups4j#31]
The cups-2.2.10-6 + deb10u1 I installed on the Raspberry Pi works fine on the Raspberry Pi, but with cups4j, I can only print .txt, not pdf, word. Is there a requirement for the version of cups？

**Comment by harwey** [comment]
You need to configure CUPS to get this working. Please check the CUPS documentation. There are different CUPS drivers you can install. 

Cups4j ist just a simple java library to easily support printing from java by sending files to CUPS printers and check print state ..
