### ISSUE TITLE
Add support for NTLM authentication

### ISSUE THREAD

**Issue by 62mkv** [harwey/cups4j#33]
Hi 

've been trying to use this library to list printers on a Windows Server

the code being: 
```
        CupsClient cupsClient = new CupsClient("t-print1.corp.domain", 631, "my.name");
        for (CupsPrinter printer: cupsClient.getPrinters()) {
            System.out.println(printer.getDescription());
        }
```

and it ends up with 

```
Exception in thread "main" java.io.IOException: HTTP error! Status code:  HTTP/1.1 401 Unauthorized
	at org.cups4j.operations.IppOperation.sendRequest(IppOperation.java:133)
	at org.cups4j.operations.IppOperation.request(IppOperation.java:67)
	at org.cups4j.operations.cups.CupsGetPrintersOperation.getPrinters(CupsGetPrintersOperation.java:56)
	at org.cups4j.CupsClient.getPrinters(CupsClient.java:106)
	at ee.mkv.demo.CupsDemoApplication.main(CupsDemoApplication.java:19)
```

with the following being in the response: 

```
Hypertext Transfer Protocol
    HTTP/1.1 401 Unauthorized\r\n
    Content-Type: text/html\r\n
    Server: Microsoft-IIS/10.0\r\n
    WWW-Authenticate: Negotiate\r\n
    WWW-Authenticate: NTLM\r\n
    X-Powered-By: ASP.NET\r\n
    Date: Fri, 28 Feb 2020 12:30:51 GMT\r\n
    Content-Length: 1293\r\n
    \r\n
```

My understanding is that there's no support of authentication whatsoever in the cups4j. Is there a way to add it or to use some other library alongside this one ?

**Comment by Julius95** [comment]
To add support for authenticated requests you can add Base64 encoded cups admin credentials to Cups request's headers. Cups4J unfortunately doesn't seem to have this functionality and I don't know any other library integrated to Cups, so unfortunately most likely you have to implement this functionality yourself. However this pr seems to add support for Cups authentication https://github.com/harwey/cups4j/pull/29 but it's been open for months now.

**Comment by harwey** [comment]
Sorry for the long delay. I was not able to work on Cups4j for quite some time.
