### ISSUE TITLE
This cups4j client only work with Cups server ? or this will work on direct IPP enable printer ?

### ISSUE THREAD

**Issue by harwey** [harwey/cups4j#39]
This cups4j client only work with Cups server ? or this will work on direct IPP enable printer ?

_Originally posted by @rohitdobariya in https://github.com/harwey/cups4j/issue_comments/710051963_

**Comment by harwey** [comment]
I think it depends on the printer you use. Cups4j has some CUPS specific methods, but most of them are IPP standard. You can give it a try, but I won't be able to support you with some printer I do not know.

**Comment by gmuth** [comment]
as usual: "it depends"
in general if you don't use any [CUPS ipp add ons](https://www.cups.org/doc/spec-ipp.html) cup4j should work.
on the other hand you can find (a limited) CUPS version embedded in ipp printers (e.g. Brother VC 500).
and you will find useful cups attributes being supported by normal printers as well, e.g. HPs support marker-levels (which are not ipp standard)
