### ISSUE TITLE
ipps protocol support in ipp operation

### ISSUE THREAD

**Issue by sureshvasu** [harwey/cups4j#45]
Adding ipps support to cups4j API while connecting to printers secured via https protocol.

**Comment by sudayar** [comment]
Hi. I am a user of this library. Currently I am using 0.7.8 version via Maven. I am also looking to use https protocol to connect to the printers. I was planning to clone this repo and make changes for my needs. Do you know when the new version will be published with https support?
Thanks.

**Comment by sureshvasu** [comment]
Hi Admin,

i am getting following error while pushing the code for ipps support, can you help?

git push --set-upstream origin ipps-support
remote: Permission to harwey/cups4j.git denied to sureshvasu.
fatal: unable to access 'https://github.com/harwey/cups4j.git/': The requested URL returned error: 403

**Comment by harwey** [comment]
Hi sureshvasu, 
you cannot push to my repository but you can create a pull task.

**Comment by sureshvasu** [comment]
Hi  Harwey,

Thanks for the reply.
Can you let me know how to do the pull task?
Is there any documentation you can provide?

Regards,
Suresh

**Comment by sureshvasu** [comment]
@harwey can you help me on the pull task?

**Comment by harwey** [comment]
Hi Sureshvasu, 
Pull requests are documented here : https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
Regards
Harald
