### ISSUE TITLE
"401 Unauthorized" in IppSendDocumentOperation

### ISSUE THREAD

**Issue by oboehm** [harwey/cups4j#6]
In some situations you'll get a 401-error you send several jobs as one job:

```java
    int id = cupsPrinter.createJob("test-job");
    String user = "james",
    PrintJob printJob = new PrintJob.Builder(content).jobName("test-job").userName(user).build();
    cupsPrinter.print(printJob, id, true);
```

If the user who is logged in is not user "james" you probably get the following error message:

```
[main] WARN ch.ethz.vppserver.ippclient.IppResponse - <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML>
<HEAD>
	<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">
	<TITLE>401 Unauthorized</TITLE>
	<LINK REL="STYLESHEET" TYPE="text/css" HREF="/cups.css">
</HEAD>
<BODY>
<H1>401 Unauthorized</H1>
<P>Enter your username and password or the root username and password to access this page. If you are using Kerberos authentication, make sure you have a valid Kerberos ticket.</P>
</BODY>
</HTML>


java.lang.NullPointerException
	at org.cups4j.operations.ipp.IppSendDocumentOperation.request(IppSendDocumentOperation.java:148)
	at org.cups4j.CupsPrinter.print(CupsPrinter.java:218)
```

# Workaround
Set the user to the user who is logged in:

```java
    ...
    String user = System.getProperty("user.name"),
    PrintJob printJob = new PrintJob.Builder(content).jobName("test-job").userName(user).build();
    ...
```

I will fix it in the next few days...

**Comment by harwey** [comment]
Thanks for your fix, I will release this fix as cups4j 0.7.4.

**Comment by harwey** [comment]
Yes, I just merged the corrections sent by oboehm that fixed the above issue in the new feature printing several documents within one print job. 
So in any way you should be fine.

**Comment by harwey** [comment]
You also can download jars from maven central repository if you do not want to build the cups4j.jar yourself.
I deployed cups4j 0.7.4 tonight, but it always takes some time (several hours sometimes) before it can be seen here: https://mvnrepository.com/artifact/org.cups4j/cups4j

**Comment by harwey** [comment]
Again upload to maven central first failed with error messages. A second upload strangely resolved the error. So Cups4j 0.7.4 and Cups4j 0.7.5 are available now. 
Both versions are identical. 
Sorry, that's my fault, but it is also not possible to remove a version uploaded to maven central in order to fix this.

**Comment by harwey** [comment]
Again thanks to oboehm (https://github.com/oboehm) for the pull request.

**Comment by oboehm** [comment]
Thank you for releasing it!
