### ISSUE TITLE
Classes support?

### ISSUE THREAD

**Issue by shambarick** [harwey/cups4j#8]
Does this library support the classes or groups of printers? 
If not, do you plan to add the support?

**Comment by harwey** [comment]
Hi Shambarick, 

Printer classes are not supported (yet). 
Cups4j mainly aims to query printers on CUPS-Servers, print documents and check job state in order to be able to signal problems or success of print jobs to applications an users. Cups4J mainly supports IPP-Operations and only some CUPS extensions so far.

As I understand printer classes are more a feature to organize printers in groups than a key feature used for printing. 

Can you describe what you want to do with it in your application? This should make it more transparent, what changes in Cups4j are needed to support classes for you.

**Comment by shambarick** [comment]
I have several printers for different specific needs: ID card, license, ...
So when I have to print an ID card, I would just create a printing job to the class "ID Card", and one of the available printers of the class would print it. Also, if I add more printers or replace them, it won't affect the application, since the only thing it needs to know is the class to use for printing.

**Comment by harwey** [comment]
That sounds interesting and might be of good use for others too. I will take a look at this and will come back to this thread.

**Comment by harwey** [comment]
So, cups4j supports printer classes already out of the box.
Say you have a class of printers called "test" and a pdf file in /tmp/test.pdf that should be printed. 

```java
 CupsClient client = new CupsClient(host, port);
    CupsPrinter printer = client.getPrinter(new URL("http://localhost:631/classes/test"));
    PrintJob printJob = new PrintJob.Builder(new FileInputStream(new File("/tmp/test.pdf"))).build();
    printer.print(printJob);
```
Please check if this works in your scenario.

**Comment by shambarick** [comment]
Thanks, just tested it, and it seems to work great.
Now I'm looking for how to get the list of classes. I didn't find how to get it with cups4j. I plan to have an API to expose the available classes, so the clients know which ones to use.

**Comment by harwey** [comment]
Printer classes contain "classes" in their CUPS URL. 
You can find your classes this way:

```java
CupsClient client = new CupsClient(host, port);
Map<String, CupsPrinter> classMap=new HashMap<String, CupsPrinter>();
       
for(CupsPrinter printer: client.getPrinters()) {
  if(printer.getPrinterURL().toString().contains("classes")) {
     classMap.put(printer.getName(),printer);
  }
}
```

**Comment by shambarick** [comment]
Thanks, I didn't notice that part. Actually the library already supports what I need :smile:

**Comment by harwey** [comment]
The current SNAPSHOT version has a method
```java
public boolean isPrinterClass()
```
on CupsPrinter class in order to ease use of printer classes.

**Comment by shambarick** [comment]
Thank you for the update.
