### ISSUE TITLE
Running in timeout

### ISSUE THREAD

**Issue by oboehm** [harwey/cups4j#9]
From time to time it happens that our CUPS server does not response within 10 seconds and we get a SocketTimeoutException. What we need is longer timeout or a configurable timeout.

**Comment by oboehm** [comment]
There is PR #10 open with a fix for this issue. Is it planned to merge it?

**Comment by harwey** [comment]
Sorry, I closed your request without merging it. Could you please reopen the PR?
Thanks.
Harald

**Comment by oboehm** [comment]
ok, I opened now a new one...

**Comment by harwey** [comment]
Finally resolved and uploaded to maven central. Sorry for the delay.
